name: 'build and test'
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout (GitHub)
      uses: actions/checkout@v3

    - name: Build and run dev container task
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/bebop/ark-devcontainer
        cacheFrom: ghcr.io/bebop/ark-devcontainer
        push: always
        # Change this to be your CI task/script
        runCmd: go test -v ./...